USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist VARCHAR(150) NOT NULL,
  name   VARCHAR(200) NOT NULL,
  release_date INT UNSIGNED NOT NULL,
  sales DECIMAL(10,5) NOT NULL,
  genre VARCHAR(100) DEFAULT "Blues",
  PRIMARY KEY (id)
);

